server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple_saga
    username: postgres
    password: q1w2e3r4
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    show-sql: true
